import type { Metadata } from "next";
import RootLayout from "./rootlayout";

export const metadata: Metadata = {
  title: "Parking Payment App",
  description: "Generated by Parking Payment App",
  icons: {
    icon: "/images/icon.png",
  },
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <RootLayout>{children}</RootLayout>;
}
