import MainLayout from "@/layouts/MainLayout";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Parking payment app",
  description: "Generated by parking payment app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const Layout = MainLayout;
  return (
    <html lang="en">
      <body style={{ margin: 0, padding: 0 }}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
