import Header from "@/components/header";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Parking payment app",
  description: "Generated by parking payment app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
