import type { Metadata } from "next";
import { ApolloWrapper } from "@/container/ApolloWrapper";
import { CssBaseline, ThemeProvider } from "@mui/material";
import theme from "@/themes";

export const metadata: Metadata = {
  title: "Parking Payment App",
  description: "Generated by Parking Payment App",
  icons: {
    icon: "/images/icon.png",
  },
};

export default function ThemeProviderWrapper({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ApolloWrapper>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        {children}
      </ThemeProvider>
    </ApolloWrapper>
  );
}
